version: 0.01
mysql:
  host: 172.16.3.158
  user: root
  pwd: 123456
  dbname: spa_catalog_items
  port: 3306
es:
  host: 127.0.0.1
  index: spa_catalog_items
  port: 9200
table:
  - name: item
    rebuild: True
    batch: 2000
    where: 
#      -
#  - name: item_trace
#    rebuild: True
#    batch: 1000
#    where:
#      -