version: 0.01
mysql:
  host: 127.0.0.1
  user: root
  pwd: root
  dbname: test_db
  port: 3306
es:
  host: 127.0.0.1
  index: test_db
  int_fields: [ 'unix_time','unix_day','grade' ]
  float_fields: [  ]
  date_fields: [ 'create_time' ]
  port: 9200
table:
  - name: test
    rebuild: false
    batch: 2000
    where:





