version: 0.01
mysql:
  host: 127.0.0.1
  user: root
  pwd: 123456
  dbname: test
  port: 123456
es:
  host: 127.0.0.1
  index: test
  port: 9200
table:
  - name: test
    rebuild: false
    batch: 2000
    where:
